apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'dagger.hilt.android.plugin'

android {
    namespace 'com.jour.demo'
    compileSdk 34
    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }
    signingConfigs {
        release {
            storeFile file('../keystore/com.jour.demo.jks')
            keyAlias = 'delun'
            storePassword 'delun123456'
            keyPassword 'delun123456'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    packagingOptions {
        // 方案 A：选择第一个找到的文件（推荐尝试这个）
        pickFirst 'assets/location_map_gps_locked.png'
        pickFirst 'assets/location_map_gps_3d.png'

        // 或者 方案 B：如果不想使用这个资源，直接排除（不推荐，除非你知道后果）
        // exclude 'assets/location_map_gps_locked.png'
    }
}

kapt {
    arguments {
        arg("AROUTER_MODULE_NAME", project.getName())
    }
    correctErrorTypes true
}
hilt {
    enableAggregatingTask = false //hilt 2.44以上版本兼容 Arouter 需要添加这个
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    //androidx
    implementation "androidx.core:core-ktx:1.12.0"
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.annotation:annotation:1.8.0'
    implementation "androidx.activity:activity-ktx:1.8.0"
    implementation "androidx.fragment:fragment-ktx:1.6.2"
    implementation 'com.google.android.material:material:1.12.0'
    implementation "androidx.collection:collection-ktx:1.4.0"

    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.7.0"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0"

    //navigation
    implementation 'androidx.navigation:navigation-fragment-ktx:2.7.6'
    implementation 'androidx.navigation:navigation-ui-ktx:2.7.6'


    //glide
    implementation 'com.google.code.gson:gson:2.9.0'
    implementation 'com.github.bumptech.glide:glide:4.15.1'
    implementation 'com.github.bumptech.glide:okhttp3-integration:4.9.0'

    //coil
    implementation "io.coil-kt:coil:2.6.0"
    implementation "io.coil-kt:coil-gif:2.6.0"
    implementation "io.coil-kt:coil-video:2.1.0"

    //retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.7.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.7.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.3'

    //hilt
    implementation "com.google.dagger:hilt-android:2.52"
    kapt "com.google.dagger:hilt-compiler:2.52"

    implementation "com.google.auto.service:auto-service:1.0"
    kapt "com.google.auto.service:auto-service-annotations:1.0"

    //arouter
    implementation 'com.alibaba:arouter-api:1.5.2'
    kapt 'com.alibaba:arouter-compiler:1.5.2'

    //room
    def room_version = "2.5.0"

    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"

    // To use Kotlin annotation processing tool (kapt)
    kapt "androidx.room:room-compiler:$room_version"
    // To use Kotlin Symbol Processing (KSP)
    //    ksp "androidx.room:room-compiler:$room_version"
    // optional - Paging 3 Integration
    implementation "androidx.room:room-paging:$room_version"

    implementation 'androidx.work:work-runtime:2.8.1'
    implementation "androidx.work:work-runtime-ktx:2.8.1"

    implementation 'com.orhanobut:logger:2.2.0'
    implementation 'org.jsoup:jsoup:1.21.2'
//  implementation 'com.zhy:base-rvadapter:3.0.3'

    implementation 'io.jsonwebtoken:jjwt:0.13.0'

    implementation 'com.github.li-xiaojun:FlycoTabLayout:2.0.8'
    implementation 'io.github.youth5201314:banner:2.2.3'
    implementation 'com.blankj:utilcodex:1.31.1'

    implementation 'com.github.lygttpod:SuperTextView:2.4.6'
    implementation 'com.github.getActivity:ShapeView:9.2'

    implementation 'com.google.android.flexbox:flexbox:3.0.0'
    implementation 'com.github.iwgang:countdownview:2.1.6'

    implementation 'io.github.lucksiege:pictureselector:v3.10.6'
    implementation "io.github.lucksiege:compress:v3.10.6"
    implementation "io.github.lucksiege:ucrop:v3.10.6"

    implementation 'com.guolindev.permissionx:permissionx:1.8.1'
    implementation 'com.github.li-xiaojun:XPopup:2.10.0'

    implementation 'id.zelory:compressor:3.0.1'

    implementation 'com.amap.api:3dmap:latest.integration'
//  implementation 'com.amap.api:search:latest.integration'
      implementation 'com.amap.api:map2d:latest.integration'
//  implementation 'com.amap.api:location:latest.integration'

    debugImplementation 'cat.ereza:customactivityoncrash:2.4.0'
    implementation 'com.github.Dimezis:BlurView:version-2.0.6'

    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'
}
